### ISSUE TITLE
alembic upgrade head

### ISSUE THREAD

**Issue by l3zha** [ChronoDi/HomeAssistBot#1]
Получаю следующую ошибку, подскажите, пжлста, что делать?)

> alembic upgrade head
> Traceback (most recent call last):
>   File "/home/oleg/HomeAssistBot/venv/bin/alembic", line 8, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "/home/oleg/HomeAssistBot/venv/lib/python3.11/site-packages/alembic/config.py", line 632, in main
>     CommandLine(prog=prog).main(argv=argv)
>   File "/home/oleg/HomeAssistBot/venv/lib/python3.11/site-packages/alembic/config.py", line 626, in main
>     self.run_cmd(cfg, options)
>   File "/home/oleg/HomeAssistBot/venv/lib/python3.11/site-packages/alembic/config.py", line 603, in run_cmd
>     fn(
>   File "/home/oleg/HomeAssistBot/venv/lib/python3.11/site-packages/alembic/command.py", line 385, in upgrade
>     script.run_env()
>   File "/home/oleg/HomeAssistBot/venv/lib/python3.11/site-packages/alembic/script/base.py", line 582, in run_env
>     util.load_python_file(self.dir, "env.py")
>   File "/home/oleg/HomeAssistBot/venv/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
>     module = load_module_py(module_id, path)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/oleg/HomeAssistBot/venv/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py    spec.loader.exec_module(module)  # type: ignore
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/home/oleg/HomeAssistBot/migration/env.py", line 9, in <module>
>     from tg_bot.database.models import *
>   File "/home/oleg/HomeAssistBot/tg_bot/database/models.py", line 4, in <module>
>     from tg_bot.database.base import Base
>   File "/home/oleg/HomeAssistBot/tg_bot/database/base.py", line 3, in <module>
>     from tg_bot.config_data import config
>   File "/home/oleg/HomeAssistBot/tg_bot/config_data/__init__.py", line 3, in <module>
>     config: Config = load_config()
>                      ^^^^^^^^^^^^^
>   File "/home/oleg/HomeAssistBot/tg_bot/config_data/config.py", line 46, in load_config
>     admins=list(map(int, env.list('ADMINS'))),
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ValueError: invalid literal for int() with base 10: 'Oleg'

**Comment by ChronoDi** [comment]
> Получаю следующую ошибку, подскажите, пжлста, что делать?)
> 
> > alembic upgrade head
> > Traceback (most recent call last):
> > File "/home/oleg/HomeAssistBot/venv/bin/alembic", line 8, in 
> > sys.exit(main())
> > ^^^^^^
> > File "/home/oleg/HomeAssistBot/venv/lib/python3.11/site-packages/alembic/config.py", line 632, in main
> > CommandLine(prog=prog).main(argv=argv)
> > File "/home/oleg/HomeAssistBot/venv/lib/python3.11/site-packages/alembic/config.py", line 626, in main
> > self.run_cmd(cfg, options)
> > File "/home/oleg/HomeAssistBot/venv/lib/python3.11/site-packages/alembic/config.py", line 603, in run_cmd
> > fn(
> > File "/home/oleg/HomeAssistBot/venv/lib/python3.11/site-packages/alembic/command.py", line 385, in upgrade
> > script.run_env()
> > File "/home/oleg/HomeAssistBot/venv/lib/python3.11/site-packages/alembic/script/base.py", line 582, in run_env
> > util.load_python_file(self.dir, "env.py")
> > File "/home/oleg/HomeAssistBot/venv/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
> > module = load_module_py(module_id, path)
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "/home/oleg/HomeAssistBot/venv/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py    spec.loader.exec_module(module)  # type: ignore
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "", line 940, in exec_module
> > File "", line 241, in _call_with_frames_removed
> > File "/home/oleg/HomeAssistBot/migration/env.py", line 9, in 
> > from tg_bot.database.models import *
> > File "/home/oleg/HomeAssistBot/tg_bot/database/models.py", line 4, in 
> > from tg_bot.database.base import Base
> > File "/home/oleg/HomeAssistBot/tg_bot/database/base.py", line 3, in 
> > from tg_bot.config_data import config
> > File "/home/oleg/HomeAssistBot/tg_bot/config_data/**init**.py", line 3, in 
> > config: Config = load_config()
> > ^^^^^^^^^^^^^
> > File "/home/oleg/HomeAssistBot/tg_bot/config_data/config.py", line 46, in load_config
> > admins=list(map(int, env.list('ADMINS'))),
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > ValueError: invalid literal for int() with base 10: 'Oleg'

Я прошу прощения, я только увидел сообщение :) Ошибка говорит о том, что в файле .env неверно написаны id пользователей, это должны быть целые числа, записанные через запятую без пробелов, например:
`ADMINS=4234234234,1234324231231,51312343`

**Comment by javierferwolf** [comment]
прошу прощения мне тоже получилось что-то похоже! что не так?)

 alembic upgrade head
Traceback (most recent call last):
  File "/home/javier/.local/bin/alembic", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/javier/.local/lib/python3.11/site-packages/alembic/config.py", line 632, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/javier/.local/lib/python3.11/site-packages/alembic/config.py", line 626, in main
    self.run_cmd(cfg, options)
  File "/home/javier/.local/lib/python3.11/site-packages/alembic/config.py", line 603, in run_cmd
    fn(
  File "/home/javier/.local/lib/python3.11/site-packages/alembic/command.py", line 385, in upgrade
    script.run_env()
  File "/home/javier/.local/lib/python3.11/site-packages/alembic/script/base.py", line 582, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/javier/.local/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javier/.local/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/javier/HomeAssistBot/migration/env.py", line 96, in <module>
    run_migrations_online()
  File "/home/javier/HomeAssistBot/migration/env.py", line 90, in run_migrations_online
    asyncio.run(run_async_migrations())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/javier/HomeAssistBot/migration/env.py", line 81, in run_async_migrations
    async with connectable.connect() as connection:
  File "/home/javier/.local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/base.py", line 127, in __aenter__
    return await self.start(is_ctxmanager=True)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javier/.local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py", line 268, in start
    await greenlet_spawn(self.sync_engine.connect)
  File "/home/javier/.local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 190, in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javier/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3264, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javier/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javier/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3288, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/javier/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javier/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1267, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javier/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/javier/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 284, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javier/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javier/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/home/javier/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    with util.safe_reraise():
  File "/home/javier/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/javier/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javier/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 637, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javier/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 615, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javier/.local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 893, in connect
    await_only(creator_fn(*arg, **kw)),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javier/.local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 125, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javier/.local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 185, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/home/javier/.local/lib/python3.11/site-packages/asyncpg/connection.py", line 2092, in connect
    return await connect_utils._connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javier/.local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 895, in _connect
    raise last_error
  File "/home/javier/.local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 881, in _connect
    return await _connect_addr(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/javier/.local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 773, in _connect_addr
    return await __connect_addr(params, timeout, True, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javier/.local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 825, in __connect_addr
    tr, pr = await compat.wait_for(connector, timeout=timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javier/.local/lib/python3.11/site-packages/asyncpg/compat.py", line 56, in wait_for
    return await asyncio.wait_for(fut, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/home/javier/.local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 684, in _create_ssl_connection
    tr, pr = await loop.create_connection(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1045, in create_connection
    infos = await self._ensure_resolved(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1419, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 867, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 16] Device or resource busy
